/**
 * Service worker — offline support + installability for Arcane Interface.
 *
 * Same "no build step" philosophy as the rest of the project (see
 * verify.py / README): the precache list below is hand-maintained, mirroring
 * the app's known asset graph, rather than generated by a bundler. Add a
 * file here when you add one to index.html/src/ that the app needs offline.
 *
 * Bump CACHE_VERSION whenever shipping a build with changed assets — it's
 * the only thing that makes old cached files go away. Everything below is
 * scoped to same-origin GET requests; it never touches cross-origin traffic.
 */

const CACHE_VERSION = "v2";
const CACHE_NAME = `arcane-interface-${CACHE_VERSION}`;

const PRECACHE_URLS = [
  "./",
  "index.html",
  "manifest.webmanifest",

  "src/config.js",
  "src/main.js",
  "src/native.js",
  "src/performanceMode.js",
  "src/rotation.js",
  "src/data/spells.js",
  "src/components/ArcaneInterface.js",
  "src/components/SpellButton.js",
  "src/components/LongPress.js",
  "src/components/SpellDisplay.js",
  "src/components/ParticleLayer.js",
  "src/components/soundEngine.js",

  "src/styles/fonts.css",
  "src/styles/base.css",
  "src/styles/layout.css",
  "src/styles/button.css",
  "src/styles/spell-display.css",

  "src/assets/fonts/cinzel-latin.woff2",
  "src/assets/fonts/eb-garamond-italic-latin.woff2",
  "src/assets/fonts/eb-garamond-regular-latin.woff2",

  "icons/icon-192.png",
  "icons/icon-512.png",
  "icons/maskable-192.png",
  "icons/maskable-512.png",
];

self.addEventListener("install", (event) => {
  event.waitUntil(
    (async () => {
      const cache = await caches.open(CACHE_NAME);
      // addAll fails the whole install if any single URL 404s — this is a
      // small, fixed, hand-maintained list, so that failure mode is exactly
      // what we want (a broken precache list should be loud, not silent).
      await cache.addAll(PRECACHE_URLS);
      // Take over immediately rather than waiting for every open tab to
      // close: for a small single-page app, the risk of a page mid-session
      // briefly mixing asset versions is far smaller than the risk of a
      // user staying stuck on a stale cached build indefinitely.
      await self.skipWaiting();
    })()
  );
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    (async () => {
      const names = await caches.keys();
      await Promise.all(
        names.filter((name) => name !== CACHE_NAME).map((name) => caches.delete(name))
      );
      await self.clients.claim();
    })()
  );
});

self.addEventListener("fetch", (event) => {
  const { request } = event;
  if (request.method !== "GET") return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // Navigations (the HTML shell): network-first so a returning user gets the
  // latest build the instant they're online, falling back to the cached
  // shell when offline. Never let a stale HTML response win over a fresh one.
  if (request.mode === "navigate") {
    event.respondWith(
      (async () => {
        try {
          const fresh = await fetch(request);
          const cache = await caches.open(CACHE_NAME);
          cache.put("index.html", fresh.clone());
          return fresh;
        } catch (_) {
          const cache = await caches.open(CACHE_NAME);
          return (await cache.match("index.html")) || Response.error();
        }
      })()
    );
    return;
  }

  // Static assets: cache-first for instant, jank-free loads, with a
  // background revalidate so the cache doesn't go stale between deploys
  // that forget to bump CACHE_VERSION.
  event.respondWith(
    (async () => {
      const cache = await caches.open(CACHE_NAME);
      const cached = await cache.match(request);
      const network = fetch(request)
        .then((response) => {
          if (response && response.ok) cache.put(request, response.clone());
          return response;
        })
        .catch(() => null);
      return cached || (await network) || Response.error();
    })()
  );
});
